### PR TITLE
Remove /renovate.json, we use the one in /project

### PR DESCRIPTION
**Pull request by sideeffffect**
Congrats on the new project, btw :clap: 
/cc @adamgfraser @mijicd

### CODE REVIEW

**Comment by mijicd** [comment]
Two questions:
- Which `/project` you're referring to?
- Should it be propagated everywhere where we have renovate?

**Comment by sideeffffect** [comment]
We should be using this https://github.com/zio/zio-optics/blob/master/.github/renovate.json
Not this https://github.com/zio/zio-optics/blob/master/renovate.json (that's why I'm removing it)

Sorry, I meant to say `/.github` :facepalm:

**Comment by mijicd** [comment]
I wasn't aware what are you removing either :laughing:

**Review by mijicd — APPROVED** [review]

**Comment by adamgfraser** [comment]
@sideeffffect Thank you! 🙏

**Pull request merged**
